### ISSUE TITLE
Page title is 'Webpack App'

### ISSUE THREAD

**Issue by clarkmu** [jquense/react-big-calendar#1577]
Can you change the page title at:
https://intljusticemission.github.io/react-big-calendar/examples/index.html
?

I keep that tab open and I keep wishing it would be "Big Calendar Docs" or anything more description than "Webpack App"

Thanks for the awesome package!

**Comment by th0rgall** [comment]
I also noticed this now. It is annoying when referring to the documentation and having multiple tabs open.

I looked a bit where this problem might come from.

The file https://github.com/jquense/react-big-calendar/blob/master/examples/index.html seems correct, but I doubt that it is used, since the Webpack config of the documentation site includes a version of the [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) via jquense's own [webpack-atoms](https://github.com/jquense/webpack-atoms/tree/v8.3.0) https://github.com/jquense/react-big-calendar/blob/master/examples/webpack.config.js#L40

This repository depends on version 8.3.0 from webpack-atoms https://github.com/jquense/react-big-calendar/blob/master/yarn.lock#L13251, while the last version now is 13.1.

The issue might come from this repo, webpack-atoms v8.3.0, or its dependecy HtmlWebpackPlugin.

BTW the documentation URL in the opening post has changed to http://jquense.github.io/react-big-calendar/examples/index.html
