### ISSUE TITLE
Views WEEK shows an extra slot

### ISSUE THREAD

**Issue by ruben-kasaz** [jquense/react-big-calendar#1685]
#### Do you want to request a _feature_ or report a _bug_?

I want to report a bug.

#### What's the current behavior?

I am using react-big-calendar on my project.
I set a `min` and `max` props from 6:00 to 22:00.
The calendar renders an extra slots after the 21:00-22:00 slot.

<img width="793" alt="Capture d’écran 2020-06-22 à 17 55 31" src="https://user-images.githubusercontent.com/56114419/85308891-1ce26980-b4b2-11ea-9ad0-d2bb37638f73.png">

This slot goes from 22:00 to 23:00,

I want to hide this extra slot. Because, I can click on it, and it calls my `onSelectSlot` function, things that I don't want it to happen.

#### What's the expected behavior?

This slot should not appear since I put a `max` hours equals 22:00.

Can someone have the solution? I would appreciate that
Thank you

**Comment by vAskitsa** [comment]
This problem has been around for a long time. 
I think i created one issue in September 2019 which was related to this.
I still have this problem due i don't want hide last slot with css mess.

**Comment by bytetyde** [comment]
I've also encountered this behaviour. I think the problem comes from this line
```js
const totalMin = 1 + dates.diff(start, end, 'minutes') + getDstOffset(start, end)
```
Can be found here: https://github.com/jquense/react-big-calendar/blob/master/src/utils/TimeSlots.js#L18

If the calendar is set to show e.g 09:00 to 22:00 it will calculate (22 - 9) * 60 + _1_ => 781
And this extra Minute will result in the additional timeslot shown.

I'm not sure if there is a reason behind the additional minute or if this is just a safe guard against 0
If this is just to prevent a 0 I think an easy fix would be to use Math.max

```js
var totalMin = Math.max(1, dates.diff(start, end, 'minutes') + getDstOffset(start, end));
```

Maybe @jquense can give more context.

**Comment by cdaz5** [comment]
My workaround for this was to subtract 1 minute from the max time.  For times ending on the hour it works as expected. For times that end during the hour (say 7:30) it will still render the entire 7-8 slot, but if you click on the 7:31-8pm area the time passed will be 7:30 not matter what you clicked (small edge case to the workaround but thought i'd mention it).

**Comment by cutterbl** [comment]
resolved
