### ISSUE TITLE
scrollToTime is causing the calendar to scroll to the top onClick prev/next week

### ISSUE THREAD

**Issue by mikeyyyzhao** [jquense/react-big-calendar#1717]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
We just updated to the latest version of rbc and now when you press prev/next week, the calendar scrolls to the top regardless of where the user scrolled to before on the original week. I've tried going down to our original version (0.21) and everything worked fine but we need the latest version (dayLayoutAlgorithm). I've also tried setting scrollToTime to different values but regardless of what I set, (null, 0, 1, 9:00am js date), it always scrolls to the bottom if the scrollToTime is there as a prop. In summary, if the scrollToTime is not a prop, the calendar scrolls to the top on prev/next week and if scrollToTime is there as a prop, it scrolls to the bottom.

https://codesandbox.io/s/competent-water-yu3tu?file=/src/App.js
- scroll down the current week -> press prev/next week -> the calendar scrolls up to midnight

#### Version:
version 0.26.0.

Note: I reverted back each version until the the auto scroll disappeared and it looks like version 0.23.0 is where this started happening.

#### What's the expected behavior?
The calendar does not scroll when the user presses next or previous week.

**Comment by mikeyyyzhao** [comment]
I think this the pr that is causing the error:

https://github.com/jquense/react-big-calendar/pull/1501/files

**Comment by dhruvgoel92** [comment]
I am still running into this problem, it's a bit weird since this does not happen on http://jquense.github.io/react-big-calendar/examples/index.html#popup (week view) as I navigate Next/Prev my scroll state is maintained. Though when I bootstrapped the example on the master branch, every time I navigate using Next/Prev the scroll state is reset to 0.

**Expectation:** My expectation as a user is scrollToTime should set the time scroll when the calendar loads. Post that when I navigate across weeks/days it should not scroll and maintain my previous state.

**Questions:**
* Is website example running a different version of RBC than master?
* Do you folks think my suggested behavior is reasonable? I suspect the following line of code: https://github.com/jquense/react-big-calendar/blob/master/src/TimeGrid.js#L79 which was added as a feature here: https://github.com/jquense/react-big-calendar/pull/122
* If not, can we add functionality to disable autoScroll?

**Comment by cutterbl** [comment]
The default, of `scrollToTime`, is the 'startOf' the day. This is a pretty reasonable expectation. The prop is available so that the developer can override this default behavior.

Your suggestion for allowing to disable autoScroll is a good one though. I suggest you create a new Issue and file a Feature Request. Or, submit your own PR for approval (for reference, autoScroll is applied in the `TimeGrid.applyScroll()` method).

**Comment by dhruvgoel92** [comment]
@cutterbl makes sense, I have a Feature + PR out for this: https://github.com/jquense/react-big-calendar/pull/2137
