### ISSUE TITLE
popper.js

### ISSUE THREAD

**Issue by noctua84** [jquense/react-big-calendar#1776]
I got a deprecated warning for popper.js@1.16.1 while installing react-big-calendar via npm.
Possibly a dependency that needs to be updated in the future.

**Comment by ehahn9** [comment]
react-big-calendar uses an old version of react-overlays, which in turn uses popper 1.x. The current react-overlays uses @popper.js 2.x.

Alas, it doesn't appear trivial to upgrade to a newer react-overlays (I tried, but don't have the skills).

This turns out to be a more serious problem than one might think because it appears that using react-big-calendar in an app which also uses popper 2.0 breaks r-b-c drag & drop (!). So, for example, react-semantic-ui can't be used with r-b-c at the moment because of the popper version conflict (methinks, not 100% sure).

Which is a long way of saying +1 for the popper (react-overlays) dependency update ;-).

**Comment by ehahn9** [comment]
fixed with 0.29 (thanks @jquense)

Also, my comment above is *incorrect* - turns out the problem with DnD is the addon's use of the legacy context API (see #1795). Working on that now.
