### ISSUE TITLE
Demo renders and behaves differently from recent releases

### ISSUE THREAD

**Issue by Forfold** [jquense/react-big-calendar#1838]
#### Do you want to request a _feature_ or report a _bug_?
Bug

#### What's the current behavior?
We are currently using `react-big-calendar` in our project, and a recent issue we are working on is allowing our users to tab through events and use space/enter to select an event (like you can by clicking).

On the demo page, this is doable and works as you would expect. However, when added locally, the events are rendered as `divs` instead of `buttons`, and selecting an event via keyboard does not work (event not selected, spacebar still scrolls down page).

I'm not sure what version the demo is running on so I tested on latest (`v0.30`), as well as `v0.23.0` and `v0.22.1` since they both appear in the root `package.json`.

https://codesandbox.io/s/calendar-bare-bones-ihzzp

**Comment by jquense** [comment]
The docs end up pretty out of date, because they aren't configured to auto deploy on release, and releases are automatic (the project is basically on autopilot, i don't use it anymore and so progress comes from others PR'ing stuff). Being completely honest i don't know what version the docs are running or what the current situation is with event elements. I remember there was some back and forth on them being buttons or not to cover different a11y cases. I would suggest doing a quick survey of closed/erged PR's to see what the current state is and why.

**Comment by Forfold** [comment]
That sounds good, for my use case moving forward we're going to use material-ui wrapping the event divs to get the reader support we need, but once I have some spare time I'll be sure to look through the recent merge commits and update here if I find anything!
