### ISSUE TITLE
Consecutive short events overlapping when using dayLayoutAlgorithm="no-overlap"

### ISSUE THREAD

**Issue by pablodoble** [jquense/react-big-calendar#1843]
#### Do you want to request a _feature_ or report a _bug_?

Report a bug

#### What's the current behavior?

Hi,

when trying to display 2 short consecutive events (5min each) using `dayLayoutAlgorithm="no-overlap"`, they are overlapping like this:
![overlapping](https://user-images.githubusercontent.com/18325641/104594320-4858bb80-5671-11eb-9d37-02e6e42ba9a4.png)

The first event is from 2:00 to 2:05 and the second one from 2:05 to 2:10

You can see the bug in [this](https://codesandbox.io/s/react-big-calendar-issue-forked-64p58?file=/src/Cal.js) codesandbox (forked from #1530) 

#### What's the expected behavior?

I would expect the two events one next to the other if there is an overlap:
![notoverlapping](https://user-images.githubusercontent.com/18325641/104594779-ecdafd80-5671-11eb-9854-6e0e194bdc64.png)

Thanks in advance!

**Comment by rnegron** [comment]
We're having this issue as well, would really love to see a fix or recommended workaround!

**Comment by hcmendes** [comment]
#2240

**Comment by Guardpc** [comment]
Hello everyone!
The error occurs due to the minimum height of the event.

The fact is that the height of the event in the DOM and the height calculated via `slotMetrics.getRange()` depend on the height of the `rbc-time-column` in the DOM. Therefore, for short events we get incorrect comparisons.

The easiest way to fix this is to calculate how many percentages in the DOM the minimum height event should occupy.

By default it is [20 pixels](https://github.com/jquense/react-big-calendar/blob/1a9eb25a2b225d02a1fcf70be58d2330925818f7/src/sass/time-column.scss#L51)
For me it is 24 pixels.

I made a copy [no-overlap.js](https://github.com/jquense/react-big-calendar/blob/master/src/utils/layout-algorithms/no-overlap.js) , modified and used it as a custom dayLayoutAlgorithm.

```javascript
<Calendar
	dayLayoutAlgorithm={params => noOverlap(params)}
	...
/>
``` 

Calculate the real minimum height as a percentage in noOverlap:
```javascript
export default function ({ events, minimumStartDifference, slotMetrics, accessors }) {
	const styledEvents = overlap({
		events,
		minimumStartDifference,
		slotMetrics,
		accessors,
	});

	// get first rbc-time-column
	const RTC = document.querySelector('.rbc-time-content .rbc-time-column');
	let minHeight;

	// Calculate the real minimum height as a percentage
	if (RTC) minHeight = (26 * 100) / RTC.clientHeight;

	// It would be more correct to raise this block of code above styledEvents.sort
	for (let i = 0; i < styledEvents.length; ++i) {
		const height = styledEvents[i].style.height;

		// replace the height if necessary
		styledEvents[i].style.height = minHeight && height < minHeight ? minHeight : height;
		styledEvents[i].friends = [];
		delete styledEvents[i].style.left;
		delete styledEvents[i].style.left;
		delete styledEvents[i].idx;
		delete styledEvents[i].size;
	}

	styledEvents.sort((a, b) => {
		...
``` 

Ideally, we need to add an additional parameter for the Calendar component, but I don't have enough competence yet.

Before:
![image](https://github.com/jquense/react-big-calendar/assets/4466989/ab926642-6e94-477e-b58a-4b8fbb78d41e)


After:
![image](https://github.com/jquense/react-big-calendar/assets/4466989/d187324f-fbd7-4a6c-8889-3d96aa89cf91)

**Comment by upMel** [comment]
Hello, I stumbled upon the same issue. The PR that indicates it solved this issue doesn't seem to work.
