### ISSUE TITLE
Incorrectly shortening the multi-day event time-slot span by 1 day

### ISSUE THREAD

**Issue by croraf** [jquense/react-big-calendar#1909]
#### Do you want to request a _feature_ or report a _bug_?
bug

#### What's the current behavior?

- Check the demo's page http://jquense.github.io/react-big-calendar/examples/index.html#selectable
- select month view
- click+drag through 2 days to create an event 2 days long. The library will create an event 1 day long
- click+drag through 3 days to create an event 3 days long. The library will create an event 2 days long
- it works correctly with click and click+drag through 1 day only

react-big-calendar: v0.33.2 (I also tried locally using this git tag)
browser: Chrome, Version 89.0.4389.114 (Official Build) (64-bit)

#### What's the expected behavior?

- when click+dragging through more than 1 day timespan in month view it should correctly create events spanning through the days selected

**Comment by croraf** [comment]
I think when selecting one date on month view the `start` should be on the 00:00 of that date and `end` on 00:00 on the next date. Same with the multiday select.

**Comment by croraf** [comment]
(the same issue appears in day range select in Week view)

**Comment by mackenziekira** [comment]
Thanks for fixing this @croraf  and @pietrofxq, I was running into the same issue.

Unfortunately the merged [pull request](https://github.com/jquense/react-big-calendar/pull/1910) breaks our use case, as we use a different calendar library for our react-native mobile app. With the new change, events created from the web app (using `react-big-calendar`) display 1 day too long on our mobile app, e.g.
WEB:
<img width="967" alt="Screen Shot 2021-07-06 at 5 38 00 PM" src="https://user-images.githubusercontent.com/7525998/124683056-14708d00-de81-11eb-82fe-8f7eb056f655.png">

MOBILE:
<img width="360" alt="Screen Shot 2021-07-06 at 5 39 44 PM" src="https://user-images.githubusercontent.com/7525998/124683117-2d793e00-de81-11eb-9788-8f2b2ae885fe.png">

Could we revert this change and instead solve the problem by providing a custom `endAccessor` prop? This is what I did in our app:

```
endAccessor={(event) => {
            if (isStartOfDay(event.end)) {
              return new Date(moment(event.end).add(1, "minute").toISOString());
            } else if (event.end) {
              return event.end;
            } else {
              throw new Error("Must provide an event end time");
            }
          }}
```

Alternatively, perhaps we could instead adjust the [logic](https://github.com/jquense/react-big-calendar/blob/8e6c84db5241727548e065e4af83ef45caa734cb/src/utils/eventLevels.js#L11-L30) that sets the `span`, instead of messing w the actual end date. 

Wdyt?
