### ISSUE TITLE
Selecting time from start to end in different days not working

### ISSUE THREAD

**Issue by anwarmah** [jquense/react-big-calendar#2276]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://github.com/anwarmah/calender

### Bug description

Scheduling the start and end time within the day is working. But different days is not working. 

  const handleOpen = (calls) => {
    setCallData(callStructure);
    setCallData(f=>({ ...f, start: calls.start}));
    setCallData(f=>({ ...f, end: calls.end}))
    setOpen(true);
  }

### Expected Behavior

Start and end time different days need to work. 

### Actual Behavior

Start and end time different days not working. 

### react-big-calendar version

0.38.9

### React version

8.6.0

### Platform/Target and Browser Versions

15.2

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [X] I'm willing to open a PR

**Comment by cutterbl** [comment]
@anwarmah Without seeing the data associated with your `events` it's very hard to troubleshoot your problem, which is why we ask you to fork our [Issue Template](https://codesandbox.io/s/react-big-calendar-example-v9wdyd?file=/src/App.js) when reporting an Issue. Judging by your code it would appear that an event's `start` and `end` are strings rather than true JS Date objects. This would explain the functionality you're receiving. See our documentation on [Dates in Big Calendar](http://jquense.github.io/react-big-calendar/examples/index.html?path=/story/guides-understanding-dates--page).
