### ISSUE TITLE
Dragging and clicking background events

### ISSUE THREAD

**Issue by uffou** [jquense/react-big-calendar#2301]
### Clear and concise description of the problem

I am using background events to have events that do not overlap. But I am unable to drag and drop/ resize these events.

### Suggested solution

Ability to click, drag and resize background events

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples/index.html).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Would you like to open a PR for this feature?

- [ ] I'm willing to open a PR

**Comment by butermann** [comment]
Is it not the goal of background events to stay in the background and not be resizable/draggable? Maybe you could do what you want with normal events and another [`dayLayoutAlgorithm`](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--day-layout-algorithm)?

**Comment by vladyslavDevInmost** [comment]
@bu6n, can you recommend better way to resize shifts then?
I have normal events and shifts, how to handle drag-n-drop/resizing for both?

**Comment by cutterbl** [comment]
@vladyslavDevInmost As mentioned above, the purpose of Background Events is just that, to be in the background. They cannot be dragged or dropped or resized. The fact that they are selectable at all was an oversight by the contributor and approver of the feature, and the reason why I recently added an `isBackgroundEvent` flag to the events passed to the selection handlers, so that developers would have an easy way of ignoring selection events on Background Events without sacrificing backwards compatibility.

In a project I am working on, we use Background Events to highlight availability time blocks. We maintain a separate editor for managing the time blocks, displaying them as 'events', which allow full edit capabilities (selection, DnD, resizing, etc). When switching back to our primary scheduling display, those availability time blocks then become Background Events, which are not editable within the primary scheduling display. Aside from being a clean approach, it also allows us to separate our logic for the treatment of standard events vs background events, using entirely separate selection handlers, edit forms, and business logic.
