### ISSUE TITLE
Default date issue in the React big calendar

### ISSUE THREAD

**Issue by salmancrc** [jquense/react-big-calendar#2322]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/funny-booth-hsub7o?file=/src/App.js

### Bug description

The event is not showing on the calender when I pass the `defaultDate={new Date()}`. But when I pass the date with this format `defaultDate={new Date(2022, 12, 27)}` It shows up. Can you help me out with this issue @jquense . Thanks 

### Expected Behavior

<Calendar
          onNavigate={onNavigate}
          events={myEventsList}
          defaultDate={new Date()}
          localizer={localizer}
          step={15}
          // timeslots={8}
          defaultView='day'
          views={views}
          style={{height: 600}}
        />

### Actual Behavior

<Calendar
          onNavigate={onNavigate}
          events={myEventsList}
          defaultDate={new Date(2022, 12, 27)}
          localizer={localizer}
          step={15}
          // timeslots={8}
          defaultView='day'
          views={views}
          style={{height: 600}}
        />

### react-big-calendar version

1.5.2

### React version

18.2.0

### Platform/Target and Browser Versions

Chrome

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [x] I'm willing to open a PR

**Comment by bu6n** [comment]
This is not a bug in `react-big-calendar`.

`new Date(2022, 12, 27)` returns the 27th of January 2023!
If you are already importing `moment`, you will probably want to also use it to manipulate dates.

You don't have to pass `defaultDate={new Date()}`, because by default the calendar opens up at the current day.

See also [understanding dates](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--default-date) for how to use the `defaultDate` prop properly.
