### ISSUE TITLE
Multiple background events are overlapping with next day

### ISSUE THREAD

**Issue by abaksha-sc** [jquense/react-big-calendar#2452]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/s/react-big-calendar-example-forked-r7djnd?file=/src/App.js

### Bug description

When calendar has multiple background events for the same period then second and next events displays in next day  
  
![image](https://github.com/jquense/react-big-calendar/assets/37663273/c006238b-8974-492e-b831-c217f9c53076)

### Expected Behavior

Maybe to trim event (like usual event) will be acceptable in this case.  
Smth like following:  

![image](https://github.com/jquense/react-big-calendar/assets/37663273/bcea8c49-1226-4bfa-87c4-c990ec3f259f)
  

### react-big-calendar version

1.8.1

### React version

18.2.0

### Platform/Target and Browser Versions

Any browser/platform

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by abaksha-sc** [comment]
Maybe it will be useful for anyone as a fast workaround to just display background events in front of next day slots.
Then just add `z-index: 1` for selector `.rbc-day-slot .rbc-background-event` (and maybe also it will require to increase `z-index` of regular events)

![image](https://github.com/jquense/react-big-calendar/assets/37663273/dcf4dd7f-17a3-41c4-b7c9-1ced3b8fd4d8)

**Comment by chazzlabs** [comment]
I've been seeing this issue lately as well. Note that this happens with the default `dayLayoutAlgorithm` (`overlap`). Changing that prop to be `no-overlap` causes a different issue altogether. I think both issues occur in the following place: 

https://github.com/jquense/react-big-calendar/blob/31c4f9b0375f57a13b244bb1c54de922a7b4291b/src/TimeGridEvent.js#L50-L51

First, it looks like the issue with the `overlap` algorithm happens because `width` is a number value which causes the resulting `calc` CSS to be invalid and the `width` property not to be set. Conversely, when the algorithm is set to `no-overlap` the resulting `width` value is actually a valid CSS `calc` statement and therefore the resulting `width` style contains a nested `calc` statement which _is_ valid and resolves properly in the browser.

Next, the `no-overlap` issue I think comes from the `xOffset` being a string that represents a CSS `calc` statement. This causes `Math.max` to return `NaN` which ultimately results in the event styling to be `left: NaN%` which is also invalid. 

I've forked the above Codesandbox to demonstrate the issue with `no-overlap`. Note in the screenshot/sandbox that there are two overlapping background events on Wednesday since `left` is not set properly for what should be the right-most event.

https://codesandbox.io/p/sandbox/react-big-calendar-example-forked-3znj83

![Screenshot 2024-02-14 at 1 57 22 PM](https://github.com/jquense/react-big-calendar/assets/3136972/8bd48c10-774a-4f0b-a391-c8ee0e8c4c4a)

I'd be willing to implement a fix for this, but in the meantime I'd love to hear any additional insight/opinions.

**Comment by cutterbl** [comment]
@chazzlabs You file a PR, with some test layout in Storybook, and I'll take a look.

**Comment by chazzlabs** [comment]
I made the following PR to fix this issue. It seems like linking via the PR title isn't working so linking it here for visibility.

https://github.com/jquense/react-big-calendar/pull/2510
