### ISSUE TITLE
Clicking backgroundEvent triggers onSelectSlot

### ISSUE THREAD

**Issue by DianaLaa** [jquense/react-big-calendar#2618]
### Check that this is really a bug

- [X] I confirm

### Reproduction link

https://codesandbox.io/p/sandbox/react-big-calendar-example-forked-vpt5d8

### Bug description

Reproduction scenario:

- Click BackgroundEvent
- Expected: `onSelectEvent` is called
- Actual: `onSelectSlot` is called, then `onSelectEvent` is called

This occurs when the calendar has prop `selectable` or `selectable='ignoreEvents'`

### Expected Behavior

When clicking a backgroundEvent, do not trigger `onSelectSlot`.

### Actual Behavior

When clicking backgroundEvent, first `onSelectSlot` is called, then `onSelectEvent` is called

### react-big-calendar version

1.12.2

### React version

18.3.1

### Platform/Target and Browser Versions

Chrome latest

### Validations

- [X] Read the [docs](http://jquense.github.io/react-big-calendar/examples).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.
- [X] Make sure this is a react-big-calendar issue and not an implementation issue

### Would you like to open a PR for this bug?

- [ ] I'm willing to open a PR

**Comment by geraldhoxha95** [comment]
@DianaLaa Have a fix here: https://github.com/jquense/react-big-calendar/pull/2619

Root of the issue is that, when determining if `onSelectSlot` should be triggered, it uses the `isEvent` function, which only considers a node with class `rbc-event` as an event, and not `rbc-background-event`

Although I am not sure if this is actually a bug or working as expected, @jquense might need to chime in here.

**Comment by cutterbl** [comment]
This behavior has been in place since background events were introduces. Because there are people that use this we cannot change it to ignore it. However we did make changes to the [onSelectEvent](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--on-select-event) to provide details to differentiate if you need to ignore. As the documentation on that link states

> Clicking on a [backgroundEvent](https://jquense.github.io/react-big-calendar/examples/iframe.html?viewMode=docs&id=props--backgroundevents&args=) will also fire the onSelectEvent callback. It will also receive the backgroundEvent as the event object, but contain a isBackgroundEvent property set to true. This will allow you to distinguish between a background event and a regular event within your onSelectEvent handler.

**Comment by cutterbl** [comment]
@geraldhoxha95 And yes, `onSelectSlot` should fire, as events would overlay on top of background events. (such as using them to show availability time frames)

**Comment by DianaLaa** [comment]
Hello, thank you for your investigation and quick replies. I understand your hesitation in introducing a breaking change.

I've digged some deeper into our production code and I have some follow-up questions I hope you're willing to provide a little support with:

- Is there some way I can detect in my `onSelectSlot` handler that a backgroundEvent was clicked and that I can abort the handler because `onSelectEvent` is going to come to pass, too? (I.e. don't show a "Create new event" dialog, because the "Background event details" dialog needs to be shown)
- Is there a scenario where `onSelectEvent` is **not** triggered after `onSelectSlot` was handled? Is there a check of detached handler? This seems to happen in our production code. However, in the codesandbox I created for this ticket (see above) both handlers are called. I've tried to look into react-big-calendar source code to find this answer but I'm not familiar with it so I haven't wrapped my head around how it all ties together. 

Lastly, some curiosity: Could you help me understand with an example what is the use case for triggering both `onSelectSlot` and `onSelectEvent` when the user clicks a background event? (Not click-and-drag over a background event, not a background event with a regular event on top that is clicked, but just a regular click on a free-floating background event)

Thanks for your time.

Kind regards,
Diana

**Comment by cutterbl** [comment]
@DianaLaa I can't give you a lot of details unfortunately, as all of that functionality was written into RBC long ago. I can tell you that, personally, the product I work on uses timers and cancellation (like you see in many of our drag and drop examples in our documentation) to attempt to determine what the user's true intentions are, and only call the event it needs to in the end. My hope is that our next major version (which will be a complete rewrite and major breaking change) will address these sort of issues, but we do not have a solid timeline for that as yet.

**Comment by DianaLaa** [comment]
@cutterbl  Thank you for your reply and suggestion. I've added a check to our `onSelectSlot` method that first searches through the list of `backgroundEvents` to see if any of them was clicked. If so, the handler is exited so that `onSelectEvent` is triggered.

**Comment by simplecommerce** [comment]
Hi, I am encountering the same issue here because I am using both backgroundEvents and events, my logic was to use backgroundEvents to disable slots from being selected, while events would be actual reserved slots.

I was hoping `onSelectSlot` would not fire when clicking on backgroundEvents.

I noticed that we could pass `ignoreEvents` to selectable, I assumed it would not trigger `onSelectSlot` when clicking a background event, but unfortunately it doesn't and was wondering why.

**Comment by cutterbl** [comment]
From [our documentation of onSelectEvent](https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--on-select-event)

> Clicking on a [backgroundEvent](https://jquense.github.io/react-big-calendar/examples/iframe.html?viewMode=docs&id=props--backgroundevents&args=) will also fire the onSelectEvent callback. It will also receive the backgroundEvent as the event object, but contain a isBackgroundEvent property set to true. This will allow you to distinguish between a background event and a regular event within your onSelectEvent handler.
