### ISSUE TITLE
How can i change language of days in a week?

### ISSUE THREAD

**Issue by IceNeoMax** [jquense/react-big-calendar#697]
currently, i don't know how to change Monday or Friday into my language. How can i do that?
Many thanks

**Comment by seeyoumr** [comment]
npm install globalize or yarn add globalize，then，do require

**Comment by IceNeoMax** [comment]
@seeyoumr i already done it but this appeared
Module not found: Can't resolve 'globalize/lib/cultures/globalize.culture.fr' in '/Users/nguyen/Desktop/Code/webgiasu/front-end/src/modules/generalschedule/tabs'

**Comment by eduardoamills** [comment]
Hello

I need have the same issue, what is the content of globalize.culture file?? Where I can find that information?

Regards

**Comment by seeyoumr** [comment]
the example used moment:
`
import moment from 'moment';
moment.locale('en');
BigCalendar.setLocalizer(
 BigCalendar.momentLocalizer(moment)
);
`

**Comment by adberard** [comment]
> the example used moment:
> `import moment from 'moment'; moment.locale('en'); BigCalendar.setLocalizer( BigCalendar.momentLocalizer(moment) );`

`
TypeError: __WEBPACK_IMPORTED_MODULE_6_react_big_calendar___default.a.setLocalizer is not a function
`

> @seeyoumr i already done it but this appeared
> Module not found: Can't resolve 'globalize/lib/cultures/globalize.culture.fr' in '/Users/nguyen/Desktop/Code/webgiasu/front-end/src/modules/generalschedule/tabs'
Same error. 

 Also `Can't resolve 'cldr' in '/home/niejfklj/Documents/helj/node_modules/globalize/dist`

I dont want to use globalize as it seem that I need to modify the webpack config of the project [as seen here](https://github.com/globalizejs/globalize/issues/603)
Where can we find a working sample with moment to change the languages of the days of the week, because its not changable in the messages props.

**Comment by erald14** [comment]
downgrade globalise and then it works
